# Mukhamejan Omar - 2023
# Github: m-1o

name: app_template
description:  A Flutter App Template
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# * Application Packages and Libraries


dependencies:
  flutter:
    sdk: flutter


  # * Project Utilities
  # Localization
  flutter_localizations:
    sdk: flutter
  # Localization package
  intl: ^0.17.0
  # Flavoring
  flutter_flavorizr: ^2.1.5
  # Icon Generator
  flutter_launcher_icons: ^0.13.0
  # Native Splash Screen
  flutter_native_splash: ^2.2.15

  
  # * Navigation and routing
  # Main Router
  go_router: ^6.0.1
  # URL Launcher
  url_launcher: ^6.1.8


  # * Data Management
  # Local Data Storage
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  # Drift ORM
  drift: ^2.5.0
  # Secure Storage for sensitive data
  flutter_secure_storage: ^8.0.0


  # * Network and API
  # Http client
  dio: ^5.1.1
  # JWT Token
  jwt_decode: ^0.3.1
  # Encryption
  crypto: ^3.0.2
  # Protocol Buffers
  protobuf: ^2.1.0


  # * State Management
  # Enhanced over provider library to manage state 
  flutter_riverpod: ^2.1.1
  # BLoC pattern
  flutter_bloc: ^8.1.1
  # Reactive Programming
  rxdart: ^0.27.7


  # * Dependency Injection
  # Dependency Injection 
  injectable: ^2.1.1
  # Service Locator
  get_it: ^7.2.0


  # * File and Path Management
  # File Picker
  file_picker: ^5.2.5


  # * General Utilities
  # Object Comparison 
  equatable: ^2.0.5
   # UUID Generator
  uuid: ^3.0.4
  # Connectivity Checker
  connectivity_plus: ^3.0.2
  # Svg Images
  flutter_svg: ^2.0.5
  # Manage Permissions
  permission_handler: ^10.2.0
  # ??? Notifications 
  awesome_notifications: ^0.7.4+1

  # * Feature Utilities
  # ??? Audio Waveform Visualization
  flutter_audio_waveforms: ^1.2.1+8
  # ??? Audio Player
  audioplayers: ^4.0.1
  # ??? Tables
  pluto_grid: ^5.4.9
  # Map with Tile Layers
  flutter_map: ^3.1.0


  # * UI Utilities
  # Tool for UI adaptability
  flutter_screenutil: ^5.6.0
  # Tool for responsive UI
  responsive_framework: ^1.0.0
  # Animations
  animations: ^2.0.7
  
  
  # * Development Utilities
  # Logging 
  logger: ^1.1.0
  # DotEnv for Flutter
  flutter_dotenv: ^5.0.2
  # Crash Reporting
  sentry_flutter: ^7.4.2
  # Asset Generator
  # flutter_gen: ^5.1.0+1


  # * Formatting Utilities
  # Text Formatter for input fields
  flutter_multi_formatter: ^2.9.11


  # * Annotations
  # Freezed
  freezed_annotation: ^2.2.0
  # JSON Serialization annotations
  json_annotation: ^4.7.0


  # * UI Libraries
  # Microsoft Fluent UI
  fluent_ui: ^4.5.0
  # Fluent UI Icons
  fluentui_system_icons: ^1.1.199
  # Cupertino Icons
  cupertino_icons: ^1.0.2
  # Google Fonts
  google_fonts: ^4.0.3
  # Shimmer loading effect
  shimmer: ^2.0.0
  # Loading Indicators
  flutter_spinkit: ^5.1.0
  # Onboarding Screens
  introduction_screen: ^3.1.4
  # Showcase app features
  showcaseview: ^2.0.0+1
  # Percentage Indicator
  percent_indicator: ^4.2.2


# * Packages that will not be in the release version of app

dev_dependencies:
  # * Testing 
  # Flutter Testing Framework
  flutter_test:
    sdk: flutter
  # BLoC Testing
  bloc_test: ^9.1.1
  # Data Mocking
  mockito: ^5.3.2
  # Generate Fake Data
  faker: ^2.0.0


  # * UI Testing 
  # Preview for different devices
  device_preview: ^1.1.0
  
  
  # * Linter and code organization
  # Linter
  flutter_lints: ^2.0.0
  

  # * Code Generators
  # Generating Files 
  build_runner: ^2.3.2
  # Generating Serialization of JSON
  json_serializable: ^6.5.4
  # Code Generation for Models and Union Types
  freezed: ^2.2.0
  # Generator for local data storage
  isar_generator: ^3.0.5
  # Generating Asset Files
  flutter_gen_runner: ^5.1.0+1
  # Injecting Dependencies
  injectable_generator: ^2.1.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/splash/
    - lib/src/core/env/.env.development
    - lib/src/core/env/.env.production
    - lib/src/core/env/.env.staging


# * Flutter Icon Generator Configurations

flutter_icons:
  image_path: "assets/icons/prod.png"
  # Android Icon
  android: true
  adaptive_icon_background: "#1E1E1E"
  # iOS Icon
  ios: true
  remove_alpha_ios: true


# * Flutter Splash Screen Generator Configurations

flutter_native_splash:  
  android: true
  ios: true
  color: "FFFFFF"
  color_dark: "000000"
  image: assets/splash/light.png
  image_dark: assets/splash/dark.png
  fullscreen: true
  android_gravity: center
  ios_gravity: center
  android_12:
    image: assets/splash/light.png
    image_dark: assets/splash/dark.png
    icon_background_color: "#000000"
    icon_background_color_dark: "#000000"


# * Flutter Flavor Configurations

flavorizr: 
  app:
    android:
      flavorDimensions: "flavor-type"
      customConfig:
        minSdkVersion: 23
    ios: 
      buildSettings: {}
  flavors:
    dev:
      app:
        name: "Project Dev"
        version: "1.0.0"
        buildNumber: "1"
        icon: "assets/icons/dev.png"
      android:
        applicationId: "kz.cleverest.project-dev"
        flavorName: "Dev"
      ios: 
        bundleId: "kz.cleverest.project-dev"
    
    staging:
      app:
        name: "Project Staging"
        version: "1.0.0"
        buildNumber: "1"
        icon: "assets/icons/stage.png"
      android:
        applicationId: "kz.cleverest.project-staging"
        flavorName: "Staging"
      ios: 
        bundleId: "kz.cleverest.project-staging"

    prod:
      app:
        name: "Project"
        version: "1.0.0"
        buildNumber: "1"
        icon: "assets/icons/prod.png"
      android:
        applicationId: "kz.cleverest.project"
        flavorName: "Prod"
      ios: 
        bundleId: "kz.cleverest.project"

    