# Mukhamejan Omar - 2023
# Github: m-1o

name: app_template
description:  Drone Searcher and Aiming Desktop App
publish_to: 'none' 

version: 1.0.0+1

isar_version: 3.0.5

environment:
  sdk: ">=2.17.0 <3.0.0"

# * Packages that will be in the final version of app
dependencies:
  flutter:
    sdk: flutter

  # * Project Utilities
  # Localization
  flutter_localizations:
    sdk: flutter
  # Localization package
  intl: ^0.18.0 
  # Flavoring
  flutter_flavorizr: ^2.1.5
  # Icon Generator
  flutter_launcher_icons: ^0.11.0
  # Native Splash Screen
  # flutter_native_splash: ^2.2.15
 

  
  # * Navigation and routing
  go_router: ^6.0.1
  # * Data Management
  # Local Data Storage
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1 # contains the binaries
  flutter_secure_storage: ^8.0.0
  # Key Value Storage
  shared_preferences: ^2.1.0
  # Http client
  dio: ^4.0.6
  # JWT Token
  jwt_decode: ^0.3.1
  # Encryption
  crypto: ^3.0.2
  # UDP Socket
  udp: ^5.0.3
  # Queue of the Futures
  queue: ^3.1.0+2
  # Asset Generator
  # flutter_gen: ^5.1.0+1


  # * State Management
  # Enhanced over provider library to manage state 
  flutter_riverpod: ^2.1.1
  # BLoC pattern
  flutter_bloc: ^8.1.1

  # * RxDart
  # RxDart for notiifications
  rxdart: ^0.27.7


  # * Utilities
  # Tool for UI adaptability
  flutter_screenutil: ^5.8.4
  # Object Comparison 
  equatable: ^2.0.5
  # Image Picker from Gallery
  image_picker: ^0.8.6
  # Image Cropper
  image_cropper: ^3.0.1
  # Native File Picker
  file_picker: ^5.2.5
  # Text Formatter for input fields
  flutter_multi_formatter: ^2.9.11
  # Logging 
  logger: ^1.1.0
  # UUID Generator
  uuid: ^3.0.4
  # Functional Programming in Dart 
  fpdart: ^0.4.0
  # DotEnv for Flutter
  flutter_dotenv: ^5.0.2
  # Svg Images
  flutter_svg: ^1.1.6
  # URL Launcher
  url_launcher: ^6.1.8
  # Animations
  animations: ^2.0.7
  # Cache Images
  cached_network_image: ^3.2.3
  # Service Locator
  get_it: ^7.2.0
  # Map
  flutter_map: ^4.0.0
  # Map Tile Caching
  flutter_map_tile_caching: ^8.0.0
  # Map Utility
  latlong2: ^0.8.1
  # Map Polyline
  flutter_polyline_points: ^1.0.0
  # Stream Transformer
  stream_transform: ^2.1.0
  # Path Provider
  path_provider: ^2.0.14
  # File System
  archive: ^3.3.7


  # * Annotations
  # Freezed
  freezed_annotation: ^2.2.0
  # JSON Serialization annotations
  json_annotation: ^4.7.0

  # * UI
  # Cupertino Icons
  cupertino_icons: ^1.0.2
  # Google Fonts
  google_fonts: ^4.0.4
  # Shimmer loading effect
  shimmer: ^2.0.0
  # Adds dashed border to any widget
  dotted_border: ^2.0.0+3
  # Loading Indicators
  flutter_spinkit: ^5.1.0
  # Render Lottie Animations
  lottie: ^2.2.0
  # Onboarding Screens
  introduction_screen: ^3.1.4
  # Showcase app features
  showcaseview: ^2.0.0+1
  # Percentage Indicator
  percent_indicator: ^4.2.2
  dart_vlc: ^0.4.0

  # Staggered Grid View
  flutter_staggered_grid_view: ^0.6.2
  



dependency_overrides: 


# * Packages that will not be in the final version of app
dev_dependencies:
  # * Testing 
  # Unit Testing
  flutter_test:
    sdk: flutter
  # Data Mocking
  mockito: ^5.4.1
  # Generate Fake Data
  faker: ^2.0.0
  
  # * Linter and code organization
  # Linter
  flutter_lints: ^2.0.0
  

  # * Code Generators
  # Generating Files 
  build_runner: ^2.3.2
  # Generating Serialization of JSON
  json_serializable: ^6.5.4
  # Factory based Code Generation
  freezed: ^2.2.0
  # Generating Asset Files
  flutter_gen_runner: ^5.1.0+1
  # Isar Code Generator
  isar_generator: ^3.1.0


flutter_icons:
  image_path: "assets/app_icons/prod.png"
  # Android Icon
  android: true
  adaptive_icon_background: "#1E1E1E"
  # iOS Icon
  ios: true
  remove_alpha_ios: true
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
  linux:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  generate: true
  uses-material-design: true

  # assets:
  #   - assets/icons/
  #   - assets/splash/
  #   - assets/app_icons/
  #   - assets/map/
    # - lib/src/core/env/.env.development
    # - lib/src/core/env/.env.production
    # - lib/src/core/env/.env.staging

# Flutter Splash Screen Generator Configurations
flutter_native_splash:  
  android: true
  ios: true
  macos: true
  color: "FFFFFF"
  color_dark: "000000"
  image: assets/splash/light.png
  image_dark: assets/splash/dark.png
  fullscreen: true
  android_gravity: center
  ios_gravity: center
  android_12:
    image: assets/splash/light.png
    image_dark: assets/splash/dark.png
    icon_background_color: "#000000"
    icon_background_color_dark: "#000000"